### ISSUE TITLE
How to secure server?

### ISSUE THREAD

**Issue by ghost** [Kolyunya/afdns#3]
I ran this script on a new Digital Ocean server using the Docker 1-click-app. Everything seems to be working fine.

How do I further secure the new server. I see this script opens port 53. Outside of the docker can I close all port except SSH and 53, or does Docker need to listen on some other port?

I want to lock down the server that Docker is running on without disabling the new DNS server this script creates.

**Comment by Kolyunya** [comment]
@git-sgmoore if your are using the server as a dedicated DNS server (no other services run on it), you can forbid all connections to your external network interface (**not** the one docker server creates) except TCP/22, TCP/53 and UDP/53. This should be done on your host machine and has nothing to do with this particular container.
